### ISSUE TITLE
Sql Timeout

### ISSUE THREAD

**Issue by remijarry** [PacktPublishing/ASP.NET-Core-3-and-Angular-9-Third-Edition#1]
Hello,

I'm coding along with your book and I have a major problem whenever I launch the app. Fetching the data is either extremely slow or I get timed out. Here is the exception: 

`Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
Microsoft.Data.SqlClient.SqlException (0x80131904): Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.
 ---> System.ComponentModel.Win32Exception (258): Dépassement du délai d'attente.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__164_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at WorldCities.Data.ApiResult`1.CreateAsync(IQueryable`1 source, Int32 pageIndex, Int32 pageSize, String sortColumn, String sortOrder, String filterColumn, String filterQuery) in E:\Software development\Portfolio\Projects\WorldCities\Data\ApiResult.cs:line 77
   at WorldCities.Controllers.CitiesController.GetCities(Int32 pageIndex, Int32 pageSize, String sortColumn, String sortOrder, String filterColumn, String filterQuery) in E:\Software development\Portfolio\Projects\WorldCities\Controllers\CitiesController.cs:line 34
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
ClientConnectionId:42b3bf42-7977-4fc2-a127-afa95f02fc0f
Error Number:-2,State:0,Class:11`

If I wait long enough (like a really long time), the fetching is getting better (after loads of refreshes). I've tried with the chapter_07 repo and have the same issue.

**Comment by Darkseal** [comment]
Hi Remi,

Chapter 7 has paging enabled, therefore you should call the `GetCities` API using a `pageSize` of 10: can you confirm that? (place a debug breakpoint on **CitiesController.cs** on the first line of the `GetCities()` method to check it).

Assuming such scenario, here's the underlying SQL query:

```
SELECT [c].[Id], [c].[Name], [c].[Lat], [c].[Lon], [c0].[Id] AS [CountryId], [c0].[Name] AS [CountryName]
FROM [Cities] AS [c]
INNER JOIN [Countries] AS [c0] ON [c].[CountryId] = [c0].[Id]
ORDER BY [c].[Name]
OFFSET 0 ROWS FETCH NEXT 10 ROWS ONLY
```

The above query can be obtained using the EF debugging techniques that you can find in page 430 (Chapter 8). If you run the Chapter 9's WorldCities app, you will be able to fetch it from the `sql` string variable in the **ApiResult.cs file** (line 96).

Check that your query is identical to mine, then try to execute it using on your DB using SSMS and see how much time it takes: it's a very light query, it should take a bunch of milliseconds to complete. If it doesn't, there's a high chance that the issue relies on your SQL Server instance.

**Comment by remijarry** [comment]
I've tried those requests

https://localhost:5001/api/cities => very fast
https://localhost:5001/api/cities/?pageIndex=0&pageSize=10 => very fast
https://localhost:5001/api/cities/?pageIndex=0&pageSize=10&sortColumn=name => very very slow and sometimes get the above error

To answer your question, I confirm that pageSize is set to 10.

**Comment by Darkseal** [comment]
That line "fires" the above query: you need to try that using SSMS (not API) and benchmark it. There must be something odd in the name column and/or in the DMBS itself.

**Comment by remijarry** [comment]
I have implemented the ToSql method extensions, this is the query I get when reaching GetCities()

`SELECT [c].[Id], [c].[Name], [c].[Lat], [c].[Lon], [c0].[Id] AS [CountryId], [c0].[Name] AS [CountryName]
FROM [Cities] AS [c]
INNER JOIN [Countries] AS [c0] ON [c].[CountryId] = [c0].[Id]
ORDER BY [c].[Name]
OFFSET @__p_0 ROWS FETCH NEXT @__p_1 ROWS ONLY`

and here is the message I get from SSMS

`Msg 137, Level 15, State 2, Line 5
Must declare the scalar variable "@__p_0".
Msg 137, Level 15, State 2, Line 5
Must declare the scalar variable "@__p_1".`

**Comment by Darkseal** [comment]
Replace p0 and p1 with the actual values (you can see them if you put a breakpoint, execute the command and look at the output window with the "debug" log active): they should respectively be 0 and 10, just like I wrote early on.

Please check the query with SSMS to see if the slowness is there.

**Comment by remijarry** [comment]
everything works fine in SSMS when I replace `@__p_0 `and `@__p_1` with respectively 0 and 10.

**Comment by remijarry** [comment]
I have noticed that if I wait a few minutes without touching anything and then click on cities or countries, everything works fine and is fast

**Comment by Darkseal** [comment]
Definitely a mistery: I cannot reproduce it by any means.
